# Generated by Django 3.1 on 2021-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('smsbody', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
