# Generated by Django 3.1 on 2021-02-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(blank=True, max_length=300, null=True)),
                ('division_short_code', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaugeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('river_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GaugeReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('wlreading', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gauge_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.gaugelocation')),
            ],
        ),
        migrations.CreateModel(
            name='GaugeAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.divisionnames')),
                ('gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.gaugelocation')),
            ],
        ),
    ]
