# Generated by Django 3.1 on 2021-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wldata', '0005_gaugelocation_danger_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaugelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gaugelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
