# Generated by Django 2.0.3 on 2019-07-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0003_auto_20190714_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceimage',
            old_name='cheque_image',
            new_name='invoice_image',
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='Invoice_no',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
