# Generated by Django 2.0.3 on 2019-07-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0006_auto_20190714_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure_details',
            old_name='Cheque_details_id',
            new_name='Invoice_details_id',
        ),
        migrations.RemoveField(
            model_name='expenditure_details',
            name='Financial_year',
        ),
    ]
