# Generated by Django 2.2.3 on 2019-07-15 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0007_auto_20190714_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure_details',
            old_name='Invoice_details_id',
            new_name='Invoice_details',
        ),
        migrations.CreateModel(
            name='Expenditure_details2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gob', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Dpa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Rpa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Budget_allocation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pac.Budget_allocation')),
                ('Invoice_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pac.Invoice_details')),
            ],
        ),
    ]
