# Generated by Django 2.0.3 on 2019-07-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0010_auto_20190715_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure_details',
            old_name='Budget_allocation_id',
            new_name='Budget_allocation',
        ),
    ]
