# Generated by Django 2.0.3 on 2019-07-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0017_auto_20190720_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure_details',
            name='Budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.Budget_allocation'),
        ),
        migrations.AlterField(
            model_name='expenditure_details',
            name='Invoice_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.Invoice_details'),
        ),
    ]
