# Generated by Django 3.0.8 on 2020-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0021_auto_20200729_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_allocation',
            name='Report_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
