# Generated by Django 3.1 on 2020-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0022_budget_allocation_report_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='Description',
            field=models.CharField(max_length=600),
        ),
    ]
