# Generated by Django 3.1 on 2020-08-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0023_auto_20200816_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='document_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pac.invoiceimage'),
        ),
    ]
