# Generated by Django 3.0.8 on 2020-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_intervention',
            name='financial_weight',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contract_intervention',
            name='physical_weight',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=8),
        ),
    ]
