# Generated by Django 2.1.7 on 2019-02-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPPInterVention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('start_chainage', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('finish_chainage', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('vent_no', models.IntegerField(blank=True, null=True)),
                ('dpp_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='haor',
            name='population',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dppintervention',
            name='haor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.Haor'),
        ),
    ]
