# Generated by Django 3.0.8 on 2020-08-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20200807_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualitativeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ivt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Contract_Intervention')),
            ],
        ),
    ]
