# Generated by Django 2.1.7 on 2019-02-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_auto_20190220_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_eng_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_engg', to=settings.AUTH_USER_MODEL)),
                ('contract_component_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.ContractComponent')),
                ('contract_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='DPP_Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('start_chainage', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('finish_chainage', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('vent_no', models.IntegerField(blank=True, null=True)),
                ('dpp_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('haor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.Haor')),
                ('worktype_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.WorkType')),
            ],
        ),
        migrations.RemoveField(
            model_name='dppintervention',
            name='haor_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='consultant_eng_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='contract_component_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='field_eng_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='haor_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='site_eng_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='worktype_id',
        ),
        migrations.AlterField(
            model_name='progressitem',
            name='intervention_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.Contract_Intervention'),
        ),
        migrations.DeleteModel(
            name='DPPInterVention',
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='dpp_intervention_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.DPP_Intervention'),
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='exen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='field_eng_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_engg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='sde_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sde', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='site_eng_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_engg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract_intervention',
            name='so_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so', to=settings.AUTH_USER_MODEL),
        ),
    ]
