# Generated by Django 3.1 on 2020-08-13 13:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_dpp_intervention_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_intervention',
            name='dpp_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='haor',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
