# Generated by Django 3.0.8 on 2020-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_qualitativestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitativestatus',
            name='current_progress',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='qualitativestatus',
            name='overall_status',
            field=models.CharField(choices=[('C', 'Completed'), ('OG', 'On Going'), ('P', 'Problamatic')], default='OG', max_length=100),
        ),
        migrations.AddField(
            model_name='qualitativestatus',
            name='problems',
            field=models.CharField(choices=[('LA', 'Land Acquisition'), ('SR', 'Structure Relocated'), ('LP', "Local Peoplles's Obstruction"), ('RE', 'River Erosion'), ('GC', ' inappropriate Sub-surface Condition'), ('NP', 'None'), ('OT', 'Others')], default='NP', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='egp_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
