# Generated by Django 2.1.5 on 2019-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progress_quantity_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='wtype',
            field=models.CharField(choices=[('EMB', 'Embankment'), ('SUBEMB', 'Submersible,Embankment'), ('EXKHL', 'Khal Rexcavation'), ('EXRIV', 'River Reexcavation'), ('REG', 'Regulator'), ('CASW', 'Cause Way'), ('IRIN', 'Irigation Inlet'), ('WMGO', 'WMG Office'), ('BOXSL', 'Box Sluice')], max_length=30),
        ),
    ]
