# Generated by Django 3.0.8 on 2020-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20200808_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitativestatus',
            name='value_of_work_done',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
