# Generated by Django 3.1 on 2020-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20200813_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haor',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
