# Generated by Django 2.1.5 on 2019-02-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20190221_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='TIN_No',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Vat_registration',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='egp_id',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='tradelicense',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
