# Generated by Django 3.1 on 2020-08-14 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20200814_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haor',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
