# Generated by Django 3.1 on 2020-08-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_auto_20200814_2022'),
    ]

    operations = [
    ]
