# Generated by Django 3.1 on 2020-08-16 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_auto_20200814_2022'),
    ]

    operations = [
	migrations.AddField(
            model_name='contract_intervention',
            name='dpp_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
