# Generated by Django 3.1 on 2020-08-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_auto_20200816_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_intervention',
            name='dpp_cost',
        ),
    ]
