# Generated by Django 3.1 on 2020-08-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_remove_contract_intervention_dpp_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipcNo', models.IntegerField(blank=True, null=True)),
                ('ipcName', models.CharField(blank=True, max_length=500, null=True)),
                ('ipcAmount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.contract')),
            ],
        ),
        migrations.CreateModel(
            name='SheduleItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeNo', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='IPC_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.boq')),
                ('ipc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ipc')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.sheduleitemgroup'),
        ),
    ]
