# Generated by Django 2.1.7 on 2019-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_auto_20190227_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='documents/%Y/%m/'),
        ),
    ]
