# Generated by Django 2.1.5 on 2019-03-04 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_auto_20190227_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='progressitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='progress_quantity',
            name='document_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Document'),
        ),
        migrations.AddField(
            model_name='progresschedule',
            name='progress_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.ProgressItem'),
        ),
    ]
