# Generated by Django 3.1 on 2020-08-21 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_auto_20200817_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='haor',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='qualitativestatus',
            name='problems',
            field=models.CharField(choices=[('LA', 'Land Acquisition'), ('SR', 'Structure Relocated'), ('LP', "Local Peoplles's Obstruction"), ('RE', 'River Erosion'), ('AB', 'Structure is Abandoned'), ('OV', 'Overlap With Other Project'), ('GC', ' inappropriate Sub-surface Condition'), ('NP', 'None'), ('OT', 'Others')], default='NP', max_length=100),
        ),
    ]
