# Generated by Django 2.1.5 on 2019-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_auto_20190304_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressitem',
            old_name='finshdate',
            new_name='finishdate',
        ),
    ]
