# Generated by Django 2.1.5 on 2019-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_auto_20190305_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressitem',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
