# Generated by Django 2.0.3 on 2019-03-08 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_auto_20190305_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_quantity',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
