# Generated by Django 2.0.3 on 2019-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0020_auto_20190322_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpp_intervention',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('HAVE_CONTRACT', 'HAVE_CONTRACT'), ('HAVE_NO_CONTRACT', 'HAVE_NO_CONTRACT')], default='HAVE_NO_CONTRACT', max_length=100, null=True),
        ),
    ]
