# Generated by Django 2.0.3 on 2019-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0022_auto_20190324_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeNo', models.CharField(blank=True, max_length=100, null=True)),
                ('itemDescription', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
