# Generated by Django 2.0.3 on 2019-08-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0023_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('reate', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Schedule')),
                ('structure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Contract_Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to='measurements/structures/%Y/%m/%d/')),
                ('structure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Contract_Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueOfWorkDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('finishDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('OG', 'OG'), ('COMP', 'COMP'), ('TO_BE_STARTED', 'TO_BE_STARTED')], default='TO_BE_STARTED', max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=13, null=True)),
                ('boq_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.BoQ')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='vwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ValueOfWorkDone'),
        ),
    ]
