# Generated by Django 2.0.3 on 2019-08-31 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0025_auto_20190827_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressitem',
            name='finishdate',
        ),
        migrations.RemoveField(
            model_name='progressitem',
            name='startdate',
        ),
        migrations.AddField(
            model_name='progressitem',
            name='actualDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='actualFinishDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='actualQuantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='actualStartDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='executionStatus',
            field=models.CharField(choices=[('OG', 'OG'), ('COMP', 'COMP'), ('TO_BE_STARTED', 'TO_BE_STARTED'), ('HALTED', 'HALTED'), ('ABANDONED', 'ABANDONED')], default='TO_BE_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='plannedDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='plannedFinishDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='plannedStartDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='workSequenceNumber',
            field=models.IntegerField(default=0),
        ),
    ]
