# Generated by Django 2.0.3 on 2019-08-31 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0027_landacquisitiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LADocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(upload_to='structures/%Y/%m/%d/')),
                ('issuing_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LandAcquisitionStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepName', models.CharField(choices=[('0', 'Budget_Allocation'), ('1', 'Approval_From_MOWR'), ('2', 'Proposal_Submission'), ('3', 'DLAC_Meeting'), ('4', 'Notice_Under_Serctioin_4(1)'), ('5', 'Joint_List_Under_Sec_3(6)'), ('6', 'Approval_MOL'), ('7', 'Notice_Under_Sec_7'), ('8', 'Award_List_Under_Sec_8'), ('9', 'Fund_Transfer_DC'), ('10', 'Payment_Of_Compensation'), ('11', 'Possesioin_Of_Land')], default='0', max_length=50)),
                ('stepStaus', models.CharField(choices=[('OG', 'OG'), ('COMP', 'COMP'), ('TO_BE_STARTED', 'TO_BE_STARTED'), ('HALTED', 'HALTED'), ('ABANDONED', 'ABANDONED'), ('RFUSED', 'REFUSED')], default='TO_BE_STARTED', max_length=50)),
                ('dateOfCompletion', models.DateField(blank=True, null=True)),
                ('laCase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.LandAcquisitionData')),
            ],
        ),
        migrations.AddField(
            model_name='ladocuments',
            name='LandAcquisitionStage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.LandAcquisitionStage'),
        ),
    ]
