# Generated by Django 2.0.3 on 2019-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0028_auto_20190831_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacquisitiondata',
            name='amountOfLand',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='landacquisitiondata',
            name='laCaseNo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='landacquisitiondata',
            name='personPaidCom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landacquisitiondata',
            name='personsInAwl',
            field=models.IntegerField(default=0),
        ),
    ]
