# Generated by Django 2.0.3 on 2019-08-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0029_auto_20190831_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(upload_to='ProgressReport/%Y/%m/%d/')),
                ('issuing_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCode', models.CharField(blank=True, max_length=100, null=True)),
                ('reportName', models.CharField(blank=True, max_length=250, null=True)),
                ('startingDate', models.DateField(verbose_name=django.utils.timezone.now)),
                ('finishDate', models.DateField(verbose_name=django.utils.timezone.now)),
                ('lastSubmissionDate', models.DateField(verbose_name=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('eventStatus', models.CharField(choices=[('Live', 'Live'), ('Dead', 'Dead')], default='Live', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDate', models.DateField(verbose_name=django.utils.timezone.now)),
                ('submissionStats', models.CharField(choices=[('Submitted', 'Submitted'), ('NotSubmitte', 'NotSubmitted')], default='NotSubmitted', max_length=100)),
                ('reportEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ReportEvent')),
                ('reportingPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ladocuments',
            name='document',
            field=models.FileField(upload_to='LA/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='reportdocument',
            name='submissionStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ReportSubmissionStatus'),
        ),
    ]
