# Generated by Django 2.2.5 on 2019-10-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0031_auto_20191005_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='wtype',
            field=models.CharField(choices=[('EMBRR', 'Fulll Embnakment Rehab-Rehab Haor'), ('SUBEMBCN', 'Submersible,Embankment Construction New-Haor'), ('SUBEMBRN', 'Submersible,Embankment Rehablitation New-Haor'), ('EXKHLN', 'Khal Rexcavation New Haor'), ('EXRIVN', 'River Excavtion New Haor'), ('REGCN', 'Regulator Constyruction New Haor'), ('CASWCN', 'Causeway Connstruction New Haor'), ('IRINC', 'Irigation Inlet Construction'), ('WMGO', 'WMG Office'), ('BOXSLCN', 'Box Sluice Constuction New'), ('EXKHLR', 'Khal Rexcavation Rehablitation Haor'), ('EXRIVR', 'River Excavtion Rehab Haor')], max_length=30),
        ),
    ]
