# Generated by Django 2.2.5 on 2019-10-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0032_auto_20191005_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_intervention',
            name='contract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Contract'),
        ),
    ]
