# Generated by Django 2.2.5 on 2019-10-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0034_auto_20191006_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_quantity',
            name='progress_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ProgressItem'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='wtype',
            field=models.CharField(choices=[('IRINCN', 'Irigation Inlet Construction'), ('REGRR', 'Reinstallation/Repair of Regulator/causeway Rehab'), ('REGCN', 'Regulator Construction New Haor'), ('CASWCN', 'Causeway Connstruction New Haor'), ('BRIDGCN', 'Bridge Connstruction New Haor'), ('BOXSLCN', 'Box Sluice Constuction New'), ('EXKHLN', 'Khal Reexcavation New Haor'), ('EXRIVN', 'River Reexcavation New Haor'), ('EXKHLR', 'Khal Reexcavation Rehab Haor'), ('EXRIVR', 'River Reexcavation Rehab Haor'), ('EMBR', 'Full Embankment Repair Rehab Haor'), ('SEMBRN', 'Submersiblesible Embankment Repair New Haor'), ('SEMBCN', 'Submersiblesible Embankment Construction New Haor'), ('REGRN', 'Regulator  Repair New Haor'), ('EMBSPW', 'Embankment Slope Protection Work'), ('WMGOC', 'WMG Office Construction')], max_length=30),
        ),
    ]
