# Generated by Django 2.2.5 on 2019-10-16 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0035_auto_20191009_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdocument',
            name='submissionStatus',
        ),
        migrations.AddField(
            model_name='reportdocument',
            name='reportEvent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.ReportEvent'),
        ),
        migrations.AddField(
            model_name='reportdocument',
            name='reportingPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsubmissionstatus',
            name='reportingPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
