# Generated by Django 3.0.8 on 2020-08-05 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0036_auto_20191016_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressitem',
            name='finishdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='progressitem',
            name='startdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
