# Generated by Django 3.1 on 2021-02-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wldata', '0002_divisionnames_gaugeaccessibility_gaugelocation_gaugereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='communicationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('person_email', models.CharField(blank=True, max_length=200, null=True)),
                ('person_mobile', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaugeReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river_no', models.CharField(blank=True, max_length=30, null=True)),
                ('river_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GaugeAccessibility',
            new_name='ReportedGauge',
        ),
        migrations.RenameField(
            model_name='reportedgauge',
            old_name='divid',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='reportedgauge',
            old_name='gid',
            new_name='gauge_name',
        ),
        migrations.RemoveField(
            model_name='gaugelocation',
            name='gauge_name',
        ),
        migrations.AddField(
            model_name='gaugelocation',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.divisionnames'),
        ),
        migrations.AddField(
            model_name='gaugelocation',
            name='gauge_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='gaugelocation',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.gaugereader'),
        ),
        migrations.AlterField(
            model_name='gaugelocation',
            name='river_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wldata.river'),
        ),
    ]
