# Generated by Django 3.1 on 2021-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wldata', '0003_auto_20210219_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaugelocation',
            name='gauge_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gaugelocation',
            name='gauge_station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gaugelocation',
            name='gauge_upazila',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
