# Generated by Django 3.1 on 2021-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wldata', '0006_auto_20210219_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaugereading',
            name='datetime',
        ),
        migrations.AddField(
            model_name='gaugereading',
            name='reading_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
