# Generated by Django 2.2.3 on 2019-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0004_auto_20190714_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceimage',
            name='invoice_image',
            field=models.FileField(upload_to='invoice_docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='invoicesupporting',
            name='image',
            field=models.FileField(upload_to='invoice_docs/%Y/%m/%d/'),
        ),
    ]
