# Generated by Django 2.2.3 on 2019-07-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0005_auto_20190714_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_details',
            old_name='Bank_brach',
            new_name='Bank_branch',
        ),
    ]
