# Generated by Django 2.2.3 on 2019-07-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0008_auto_20190715_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure_details2',
            old_name='Budget_allocation_id',
            new_name='Budget_allocation',
        ),
    ]
