# Generated by Django 2.0.3 on 2019-07-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0015_auto_20190720_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_details',
            name='FinancialYear',
        ),
        migrations.RemoveField(
            model_name='invoice_details',
            name='Month',
        ),
    ]
