# Generated by Django 2.2.3 on 2019-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0018_auto_20190720_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpp_allocation',
            name='Shortdescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
