# Generated by Django 3.0.8 on 2020-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0019_dpp_allocation_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='Total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
    ]
