# Generated by Django 3.0.8 on 2020-07-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0020_auto_20200727_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_allocation',
            name='Dpp_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.Dpp_allocation'),
        ),
        migrations.AlterField(
            model_name='budget_allocation',
            name='Financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pac.FinancialYear'),
        ),
    ]
