# Generated by Django 2.1.7 on 2019-02-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
        ),
    ]
