"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os




from decouple import config, Csv
import dj_database_url


#os.environ['SECRET_KEY']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

"""Setting up environments for geodjango"""
"""  
if os.name == 'nt':
    VIRTUAL_ENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VIRTUAL_ENV_BASE, r'.\Lib\site-packages\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VIRTUAL_ENV_BASE, r'.\Lib\site-packages\osgeo\data\proj') + ';' + os.environ['PATH']

"""






#SECRET_KEY = config('SECRET_KEY')
SECRET_KEY = '79g)4t7v8uuj2kw$n=__$-b)87l=!rgm$5o$60gb2r0(p$jio_'
#DEBUG = config('DEBUG', default=False, cast=bool)
#ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

#ALLOWED_HOSTS = ['139.59.36.4','localhost','127.0.0.1']

#ALLOWED_HOSTS=['127.0.0.1','139.59.71.251']
#ALLOWED_HOSTS=['localhost']
#ALLOWED_HOSTS=['127.0.0.1']

#ALLOWED_HOSTS=[ '139.59.71.251']
ALLOWED_HOSTS=['localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'phonenumber_field',
	 'widget_tweaks',
    'reportlab',
	 'django_extensions',

    'boards.apps.BoardsConfig',
    'accounts.apps.AccountsConfig',
    'progress.apps.ProgressConfig',
    'pandas',
    'pac.apps.PacConfig',
    'wldata.apps.WldataConfig',
    'django.contrib.gis',
    'geopandas',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',

        #'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cmis3_db_new',
        'USER': 'postgres',
        'PASSWORD': '801223001_bwdb',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR, 'staticfiles'),]
LOGOUT_REDIRECT_URL='login'
LOGIN_REDIRECT_URL = 'sitehome'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
LOGIN_URL = 'login'
IMPORT_EXPORT_USE_TRANSACTIONS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

"""Email Related Setup"""
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST='smtp.gmail.com'
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True
EMAIL_PORT=465
EMAIL_HOST_USER='se.surfacewater.hydrology@gmail.com'
EMAIL_HOST_PASSWORD='801223001_bwdb'

"""Logging Configaraton """
LOGGING={
    'version':1,
    'disable_existing_loggers':False,
    'loggers':{
        'django':{
            'handlers':['file'],
            'level':'INFO'

        }
    },
    'handlers':{
        'file':{
            'level':'INFO',
            'class':'logging.FileHandler',
            'filename':'./logs/debug.log',
            'formatter':'simpleRe'


        }
    },
    'formatters':
        {'simpleRe':
            {
                'format':'{levelname}{message}',
                'style':'{',

        }
        

    },

}